version: '3'
services:
  ros2-desktop-vnc:
    build: .
    ports:
      - "6080:80"
    security_opt:
      - seccomp=unconfined
    shm_size: 512m
    volumes:
      - ./tello-ros2:/home/ubuntu/tello-ros2
